apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: benapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bencozy/Hello-word.git
    targetRevision: HEAD
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: default