apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: https://github.com/bencozy/sorokdva.git
      passwordSecret:
        name: my-git-secret
        key: password
      usernameSecret:
        name: my-git-secret
        key: username